import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Nafil Estates collects, uses, and protects your data.",
};

const LAST_UPDATED = "15 August 2026";
const SUPPORT_EMAIL = "support@nafilestates.com";

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-20">
      <p className="text-sm font-semibold text-brand-800">Legal</p>
      <h1 className="mt-2 text-4xl font-bold tracking-tight text-zinc-950">Privacy Policy</h1>
      <p className="mt-4 text-sm text-zinc-500">Last updated: {LAST_UPDATED}</p>

      <div className="prose-section mt-10 space-y-10 text-base leading-7 text-zinc-600">
        <section>
          <h2 className="text-xl font-semibold text-zinc-950">1. Who we are</h2>
          <p className="mt-3">
            Nafil Estates (&quot;Nafil Estates&quot;, &quot;we&quot;, &quot;us&quot;, or
            &quot;our&quot;) operates the Nafil Estates mobile application (the
            &quot;App&quot;), a gate access and estate management platform used by
            residents, security personnel, and estate administrators of participating gated
            communities in Nigeria. This policy explains what information we collect through
            the App, why we collect it, and the choices you have.
          </p>
          <p className="mt-3">
            By using the App, you agree to the collection and use of information in
            accordance with this policy.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-zinc-950">2. Information we collect</h2>
          <p className="mt-3">We collect information you provide directly, and information generated by using the App:</p>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>
              <span className="font-medium text-zinc-950">Account information:</span> email
              address, password (stored encrypted by our authentication provider, never in
              plain text), full name, phone number, unit/apartment number, and profile photo.
            </li>
            <li>
              <span className="font-medium text-zinc-950">Estate association:</span> which
              estate and unit you&apos;re linked to, and your role (resident, security, or
              admin).
            </li>
            <li>
              <span className="font-medium text-zinc-950">Visitor and household data:</span>{" "}
              names, phone numbers, and vehicle plate numbers of visitors and household
              members you register for gate access, and photos for household/frequent-visitor
              cards.
            </li>
            <li>
              <span className="font-medium text-zinc-950">Gate activity:</span> visitor pass
              codes, check-in and check-out timestamps, and the security officer who
              processed each check-in, recorded when a resident&apos;s pass or code is used
              at the gate.
            </li>
            <li>
              <span className="font-medium text-zinc-950">Issue reports:</span> descriptions
              and photos you submit when reporting a maintenance or estate issue.
            </li>
            <li>
              <span className="font-medium text-zinc-950">Device and notification data:</span>{" "}
              a push notification token so we can deliver announcements and alerts to your
              device, and the platform (iOS/Android) your device runs.
            </li>
            <li>
              <span className="font-medium text-zinc-950">Camera and photos:</span> the App
              requests camera access to scan visitor QR codes, and photo library access so
              you can set a profile picture or attach photos to an issue report. We only
              access these when you actively use those features.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-zinc-950">3. How we use your information</h2>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>To create and maintain your account, and verify your identity when you sign in.</li>
            <li>To generate, validate, and log visitor passes and gate check-ins for your estate.</li>
            <li>To route issue reports and announcements to the right residents, security officers, or admins.</li>
            <li>To send push notifications for announcements, emergency alerts, and updates on issues or passes you&apos;re involved in.</li>
            <li>To maintain the security of the App and the estates that use it, including detecting misuse of the platform.</li>
            <li>To respond to support requests you send us.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-zinc-950">4. Who can see your information</h2>
          <p className="mt-3">
            Information is scoped to your estate. Residents can see their own data and data
            they explicitly generate (visitor passes, household members, their own issues).
            Security officers at your estate can see visitor passes, household member codes,
            and gate check-in logs, so they can verify who&apos;s allowed through the gate.
            Estate admins can see resident directory information, issue reports, and
            announcements for their estate. We do not sell your personal information, and we
            do not share it with third parties for their own marketing purposes.
          </p>
          <p className="mt-3">
            We use third-party service providers to run the App, including Supabase for
            authentication, database, and file storage, and push notification services (Apple
            Push Notification service and Firebase Cloud Messaging) to deliver alerts. These
            providers process data on our behalf and are not permitted to use it for their own
            purposes.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-zinc-950">5. Data retention</h2>
          <p className="mt-3">
            We retain your information for as long as your account is active with an estate.
            Visitor passes and gate logs are kept as an access record for the estate. Deleting
            your account from within the App removes your profile and associated personal data
            immediately. If you request deletion by email instead, we complete it within 30
            days. Either way, we may retain certain records (for example, gate logs already tied
            to a security incident) where required for legal or safety reasons.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-zinc-950">6. Your choices</h2>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>
              <span className="font-medium text-zinc-950">Access and correction:</span> you
              can view and update most of your profile information directly in the App.
            </li>
            <li>
              <span className="font-medium text-zinc-950">Account deletion:</span> delete your
              account directly from the App under Settings &rarr; Delete my account, which
              permanently deletes your profile and associated personal data immediately. You can
              also email {SUPPORT_EMAIL} to request deletion instead. See our{" "}
              <a href="/contact" className="font-medium text-brand-800 underline">
                Support
              </a>{" "}
              page for details.
            </li>
            <li>
              <span className="font-medium text-zinc-950">Notifications:</span> you can
              disable push notifications at any time from your device settings.
            </li>
            <li>
              <span className="font-medium text-zinc-950">Camera and photos:</span> you can
              revoke camera or photo library permissions from your device settings; the App
              will ask again only when you use a feature that needs them.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-zinc-950">7. Data security</h2>
          <p className="mt-3">
            We use industry-standard measures to protect your information, including
            encrypted connections between the App and our servers, and access controls that
            restrict data to your own estate. No method of transmission or storage is 100%
            secure, and we can&apos;t guarantee absolute security.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-zinc-950">8. Children&apos;s privacy</h2>
          <p className="mt-3">
            The App is intended for use by adult residents, security personnel, and estate
            administrators. We do not knowingly collect personal information directly from
            children. A resident may register a household member of any age (for example, a
            child) for gate access; that information is provided and controlled by the
            resident acting as the account holder.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-zinc-950">9. Changes to this policy</h2>
          <p className="mt-3">
            We may update this policy from time to time. If we make material changes,
            we&apos;ll update the &quot;Last updated&quot; date above and, where appropriate,
            notify you through the App.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-zinc-950">10. Contact us</h2>
          <p className="mt-3">
            Questions about this policy or how we handle your data can be sent to{" "}
            <a href={`mailto:${SUPPORT_EMAIL}`} className="font-medium text-brand-800 underline">
              {SUPPORT_EMAIL}
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
